### ISSUE TITLE
[1.15.2]a obvious Startup Error

### ISSUE THREAD

**Issue by LearnerZ** [ldtteam/Structurize#126]
### Structurize version

Version: all version(including:structurize-0.10.285-BETA)

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. start the game
2. and goes like this
3. [img]https://s1.ax1x.com/2020/04/24/JBcA6f.png[/img]
4. ... is it the forge's problem that can not be fix or something? 

**problem log:**
[24四月2020 13:49:12.511] [modloading-worker-3/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLClientSetupEvent dispatch for modid structurize
java.lang.NullPointerException: null
	at com.ldtteam.structurize.optifine.OptifineCompat.setupReflectedMethodReferences(OptifineCompat.java:93) ~[?:0.10.223-ALPHA]
	at com.ldtteam.structurize.optifine.OptifineCompat.intialize(OptifineCompat.java:53) ~[?:0.10.223-ALPHA]
	at com.ldtteam.structurize.event.LifecycleSubscriber.onClientInit(LifecycleSubscriber.java:45) ~[?:0.10.223-ALPHA]
	at net.minecraftforge.eventbus.ASMEventHandler_16_LifecycleSubscriber_onClientInit_FMLClientSetupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?]

**Comment by Nightenom** [comment]
Please refer to conversation at #112
