### ISSUE TITLE
[1.15] crash when place supply ship

### ISSUE THREAD

**Issue by trzebiaf** [ldtteam/Structurize#139]
### Structurize version
Version: 0.10.313-RELEASE

When I place supply ship from Minecolonies 0.10.771-RELEASE, the game crash

### crash report

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 17/05/20 22:36
Description: mouseClicked event handler

java.lang.NoSuchMethodError: com.ldtteam.structures.lib.BlueprintUtils.getPrimaryBlockOffset(Lcom/ldtteam/structures/blueprints/v1/Blueprint;)Lnet/minecraft/util/Tuple;
	at com.minecolonies.coremod.client.gui.WindowMinecoloniesBuildTool.paste(WindowMinecoloniesBuildTool.java:86) ~[?:0.10.771-RELEASE] {re:classloading}
	at com.ldtteam.structurize.client.gui.WindowBuildTool.paste(WindowBuildTool.java:306) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.structurize.client.gui.WindowBuildTool.pasteNice(WindowBuildTool.java:271) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowMinecoloniesBuildTool.checkAndPlace(WindowMinecoloniesBuildTool.java:115) ~[?:0.10.771-RELEASE] {re:classloading}
	at com.ldtteam.structurize.client.gui.WindowBuildTool.confirmClicked(WindowBuildTool.java:1074) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.structurize.client.gui.WindowBuildTool$$Lambda$5640/1429024246.run(Unknown Source) ~[?:?] {}
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.lambda$registerButton$0(AbstractWindowSkeleton.java:40) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton$$Lambda$5631/829190748.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:67) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.controls.Button.handleClick(Button.java:95) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.Pane.click(Pane.java:480) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$5711/1224642639.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:141) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$5711/1224642639.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:141) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.BOScreen.mouseClicked(BOScreen.java:170) ~[?:0.10.313-RELEASE] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:82) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3617/604555852.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:80) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3616/1277118487.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3009/155953418.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(SourceFile:301) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.0.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$403/1370224403.call(Unknown Source) [forge-1.15.2-31.1.0.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.minecolonies.coremod.client.gui.WindowMinecoloniesBuildTool.paste(WindowMinecoloniesBuildTool.java:86)
	at com.ldtteam.structurize.client.gui.WindowBuildTool.paste(WindowBuildTool.java:306)
	at com.ldtteam.structurize.client.gui.WindowBuildTool.pasteNice(WindowBuildTool.java:271)
	at com.minecolonies.coremod.client.gui.WindowMinecoloniesBuildTool.checkAndPlace(WindowMinecoloniesBuildTool.java:115)
	at com.ldtteam.structurize.client.gui.WindowBuildTool.confirmClicked(WindowBuildTool.java:1074)
	at com.ldtteam.structurize.client.gui.WindowBuildTool$$Lambda$5640/1429024246.run(Unknown Source)
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.lambda$registerButton$0(AbstractWindowSkeleton.java:40)
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton$$Lambda$5631/829190748.accept(Unknown Source)
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:67)
	at com.ldtteam.blockout.controls.Button.handleClick(Button.java:95)
	at com.ldtteam.blockout.Pane.click(Pane.java:480)
	at com.ldtteam.blockout.views.View$$Lambda$5711/1224642639.accept(Unknown Source)
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307)
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271)
	at com.ldtteam.blockout.views.View.click(View.java:141)
	at com.ldtteam.blockout.views.View$$Lambda$5711/1224642639.accept(Unknown Source)
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307)
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271)
	at com.ldtteam.blockout.views.View.click(View.java:141)
	at com.ldtteam.blockout.BOScreen.mouseClicked(BOScreen.java:170)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:82)
	at net.minecraft.client.MouseHelper$$Lambda$3617/604555852.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: com.ldtteam.blockout.BOScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:80)
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163)
	at net.minecraft.client.MouseHelper$$Lambda$3616/1277118487.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162)
	at net.minecraft.client.MouseHelper$$Lambda$3009/155953418.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['trzebiaf'/235, l='MpServer', x=167.38, y=63.00, z=-100.74]]
	Chunk stats: Client Chunk Cache: 841, 550
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -815362518191415302
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (176,67,-176), Chunk: (at 0,4,0 in 11,-11; contains blocks 176,0,-176 to 191,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 440430 game time, 774842 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:568)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$403/1370224403.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1351548944 bytes (1288 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.0
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.0-client.jar Minecraft {minecraft@1.15.2 DONE}
		SereneSeasons-1.15.2-3.0.0.69-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.69 DONE}
		structurize-0.10.313-RELEASE.jar Structurize {structurize@0.10.313-RELEASE DONE}
		forge-1.15.2-31.1.0-universal.jar Forge {forge@31.1.0 DONE}
		minecolonies-0.10.771-RELEASE-universal.jar Minecolonies {minecolonies@0.10.771-RELEASE DONE}
		Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 DONE}
		gravestone-1.17.4.jar Gravestone Mod {gravestone@1.17.4 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
	Launched Version: 1.15.2-forge-31.1.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 660M/PCIe/SSE2 GL version 4.5.0 NVIDIA 364.72, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources, file/PureBDcraft  64x MC115.zip
	Current Language: Français (France)
	CPU: 8x Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz

**Comment by Asherslab** [comment]
update both versions of structurize and minecolonies to the latest alphas

**Comment by trzebiaf** [comment]
I use the last release version of both... I should be more stable then Alpha version (work in progress version) ?

**Comment by Asherslab** [comment]
no, alphas are our recommended release channel. this issue is due to mismatched versions

**Comment by someaddons** [comment]
your structurize version is much newer than your minecolonies version, so its not working with that old minecolonies version...

**Comment by someaddons** [comment]
Also the bug template clearly tells you to update BEFORE reporting...
