### ISSUE TITLE
NPE when renaming scanned schematic (Minecolonies)

### ISSUE THREAD

**Issue by Strohtaler** [ldtteam/Structurize#142]
### Structurize version

compiled from source!

Structurize: commit 4ac5ef7 (version/1.15 - yesterday)
Minecolonies: commit [4a76643](https://github.com/ldtteam/minecolonies/commit/4a76643b3611dc606dd86237108ca9e2f63474fd) (version/1.15 - yesterday)
Forge: 31.2.0
Singleplayer.

### Expected behavior
Renaming a scanned schematic should rename it and not crash the game,

### Actual behaviour
Game crashes (after saving) with NullPointerException - schematic is renamed. 
Log: [crash-client.txt](https://github.com/ldtteam/Structurize/files/4672573/crash-client.txt)
Summary:
```stacktrace
java.lang.NullPointerException: Ticking screen
	at com.ldtteam.structurize.client.gui.WindowBuildTool.onClosed(WindowBuildTool.java:465) ~[?:0.10.316-ALPHA] {re:classloading}
	at com.ldtteam.blockout.BOScreen.onClose(BOScreen.java:250) ~[?:0.10.316-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.Window.close(Window.java:241) ~[?:0.10.316-ALPHA] {re:classloading,pl:runtimedistcleaner:A}
	at com.ldtteam.structurize.client.gui.WindowBuildTool.onOpened(WindowBuildTool.java:436) ~[?:0.10.316-ALPHA] {re:classloading}
	at com.ldtteam.blockout.BOScreen.tick(BOScreen.java:232) ~[?:0.10.316-ALPHA] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$runTick$21(Minecraft.java:1365) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	...
```

### Steps to reproduce the problem
1. Scan a new schematic with the Scan Tool (or use an existing one);
2. change game mode to survival;
3. start placing the scanned schematic with the Building Tool (do **not** press the `OK`/`Accept` icon) ;
4. select the `Rename` button;
5. change the name (e.g. add or delete a letter);
6. press `Done`

5a. Alternative: `Cancel` renaming also crashed.

Obs1: pressing `ESC` closes the GUI **without** crashing.
Obs2: Could not reproduce it in Creative game mode.

**Comment by ravenbuilder934** [comment]
Is this reproducible on the latest versions?

**Comment by Strohtaler** [comment]
@ravenbuilder934  Yes, just reproduced it:
- Minecraft: 1.16.5
- Forge: 36.0.42
- Structurize: 0.13.139-ALPHA
- MineColonies: 0.13.639-ALPHA

Single-Player

same method (different line number):
```
[23Feb2021 18:48:08.286] [Render thread/FATAL] [net.minecraft.client.Minecraft/]: Reported exception thrown!

Caused by: java.lang.NullPointerException
	at com.ldtteam.structurize.client.gui.WindowBuildTool.onClosed(WindowBuildTool.java:478) ~[?:0.13.139-ALPHA]
```
Current log:
[latest.log](https://github.com/ldtteam/Structurize/files/6031400/latest.log)

**Comment by Nightenom** [comment]
Stale, probably fixed, if not please reopen
