### ISSUE TITLE
NoClassDefFoundError: net/minecraftforge/fml/DistExecutor$SafeSupplier

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [ldtteam/Structurize#159]
### Structurize version

Version: 0.10.322
Forge 31.2.0

Crashed during initialization
```
Caused by: net.minecraftforge.fml.ModLoadingException: Structurize has class loading errors
§7net/minecraftforge/fml/DistExecutor$SafeSupplier
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:77) ~[?:31.2] {re:classloading}
	at sun.reflect.GeneratedConstructorAccessor56.newInstance(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
	... 40 more
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/DistExecutor$SafeSupplier
	at com.ldtteam.structurize.Structurize.<clinit>(Structurize.java:26) ~[?:0.10.322-ALPHA] {re:classloading}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51] {}
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:71) ~[?:31.2] {re:classloading}
	at sun.reflect.GeneratedConstructorAccessor56.newInstance(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
	... 40 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.DistExecutor$SafeSupplier
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.1.0.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at com.ldtteam.structurize.Structurize.<clinit>(Structurize.java:26) ~[?:0.10.322-ALPHA] {re:classloading}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51] {}
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:71) ~[?:31.2] {re:classloading}
	at sun.reflect.GeneratedConstructorAccessor56.newInstance(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
	... 40 more
```

**Comment by someaddons** [comment]
update forge

**Comment by ravenbuilder934** [comment]
to at least 31.2.8

**Comment by Pythonic-Rainbow** [comment]
What is the last version of Structurize that supports 31.2.0?

**Comment by ravenbuilder934** [comment]
Nothing happens if you update Forge I think. Your worlds are still there.

**Comment by ToMe25** [comment]
It might sometimes be a problem with some mods tho.
The last version working with forge 31.2.0 is probably 0.10.321, not entirely sure tho.

**Comment by Pythonic-Rainbow** [comment]
Is there any reason why mods choose to use the latest version of MDK instead of the recommended version by Forge?

**Comment by ToMe25** [comment]
Forge is getting updates, bugfixes and new features, so if a version is deemed "stable enough" people tend to use it regardless of whether its a "recommended" version.

**Comment by Pythonic-Rainbow** [comment]
I personally oppose using the latest build MDK and should support the latest recommended version, but that is another story.
