### ISSUE TITLE
Netty Epoll Client IO #5/ERROR  ... Could not deserialize minecraft

### ISSUE THREAD

**Issue by ClaudiusMinimus** [ldtteam/Structurize#172]
#53 # Structurize version

Version: structurize-0.13.7-ALPHA

### Expected behavior
To be able to log on to server without having to restart the server

### Actual behaviour

I get the following message
![2020-07-04_11 23 47](https://user-images.githubusercontent.com/17887664/86517835-3c01c500-bde9-11ea-8c29-bfa38c5701b2.png)

Server [latest.log](https://github.com/ldtteam/Structurize/files/4873391/latest.log)
Client [latest.log](https://paste.ee/p/j5BbG)

### Steps to reproduce the problem

We are currently building a mod pack and in
From looking at some of the last entries in the log files, it seems Structurize may be the cause of this issue. Over the past two days, I have had to restart the server often before I relog.

1. Attempt to login to server
2. Recieve error message

**Comment by Raycoms** [comment]
```
04Jul2020 19:16:58.389] [Server thread/INFO] [STDOUT/]: [com.branders.spawnermod.event.WorldEvents:otherEvent:86]: Finished with one spawner
[04Jul2020 19:16:58.389] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 6
	Listeners:
		0: HIGHEST
		1: ASM: com.github.elrol.ElrolsUtilities.events.OnPlayerJoinHandler@40b19b4d onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		2: NORMAL
		3: ASM: class com.supermartijn642.tesseract.manager.TesseractChannelManager onJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		4: ASM: net.minecraftforge.common.ForgeInternalHandler@7f132590 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		5: ASM: class com.ldtteam.structurize.event.EventSubscriber onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		6: ASM: com.branders.spawnermod.event.WorldEvents@474f3756 otherEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		7: ASM: com.branders.spawnermod.SpawnerMod@4bcbe67e playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		8: ASM: stepsword.mahoutsukai.handlers.ServerHandler@50396417 playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		9: ASM: class com.supermartijn642.packedup.BackpackStorageManager onJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		10: ASM: net.coolsimulations.MoreThanAPickaxe.init.MoreThanAPickaxeEventHandler@5350838c onplayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		11: ASM: net.blay09.mods.trashslot.TrashSlot@4ac76953 onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		12: ASM: net.coolsimulations.SurvivalPlus.core.util.SurvivalPlusEventHandler@d83b9c3 onplayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		13: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@5c72cd0e playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at com.branders.spawnermod.event.WorldEvents.otherEvent(WorldEvents.java:63)
	at net.minecraftforge.eventbus.ASMEventHandler_155_WorldEvents_otherEvent_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:227)
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:116)
```

There are a lot of mods in here, but structurize ain't the one.

**Comment by Raycoms** [comment]
It only means it went through the list of events (which is normal) but crashed on the last of them (which was not structurize)

**Comment by ClaudiusMinimus** [comment]
Thank you for your help. I have very little Java experience and so log files are sometimes difficult to identify issues. Among the "Listeners" shown above, should I be looking at listener 13 (curios) as the culprit?

I understand this is outside of Structurize and I greatly appreciate your guidance.

Thank you,
CM

**Comment by Raycoms** [comment]
at com.branders.spawnermod.event.WorldEvents.otherEvent(WorldEvents.java:63) would be my first goto
