### ISSUE TITLE
server stuck at starting 1.15.2

### ISSUE THREAD

**Issue by perecnicek** [ldtteam/Structurize#192]
### Structurize version

Version: structurize-0.13.35-ALPHA

### Expected behavior

- 
I start the server and it loads 
### Actual behaviour

- 
I start the server but in the end he stuck at starting and we cant join to server.

![image](https://user-images.githubusercontent.com/46170414/89324805-230a5f00-d688-11ea-88de-af21f90dd92f.png)
Also i my hosting provider found this error net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
Mod §eminecolonies§r requires §6structurize§r §o0.13.35-ALPHA or above§r
§7Currently, §6structurize§r§7 is §o0.13.19-ALPHA
BUT We already play couple of days about 2 weeks everything went smooth but after restart happend this the game thinks we have wrong version but I nothing changed in the folder we have the right version what it demand structurize 0.13.35

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Nightenom** [comment]
https://www.curseforge.com/minecraft/mc-mods/structurize/files/all
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all
also ensure that you have mods in ./mods/ only

**Comment by perecnicek** [comment]
Yes i have it only in mods folder this error happend suddenly from nothing

**Comment by perecnicek** [comment]
> https://www.curseforge.com/minecraft/mc-mods/structurize/files/all
> https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all
> also ensure that you have mods in ./mods/ only

I found out that the problem is in the world when i deleted world the server generated new one and its online shloud i uplod it for you ?

**Comment by Nightenom** [comment]
that's really weird, please post full debug.log (from the latest run) using a paste site like Pastebin or Gist

**Comment by perecnicek** [comment]
> that's really weird, please post full debug.log (from the latest run) using a paste site like Pastebin or Gist

here you are
https://gist.github.com/perecnicek/272e36d31eaafe898367f3fd59d0bc48
Yes i have optifine in the mods folder but i tried run the server without it and i got same results

**Comment by Nightenom** [comment]
Please remove optifine and optiforge from the server.
Also, don't use optiforge unless you really know you need it, people often miss use it and it's causing more issues than good things, latest optifine versions usually don't need it in 99% cases
Minecolonies is not latest minecolonies-0.13.88-BETA
Reupload debug.log (don't forget to delete the old one) if the issue persists after remove optifine related things

**Comment by perecnicek** [comment]
> Please remove optifine and optiforge from the server.
> Also, don't use optiforge unless you really know you need it, people often miss use it and it's causing more issues than good things, latest optifine versions usually don't need it in 99% cases
> Minecolonies is not latest minecolonies-0.13.88-BETA
> Reupload debug.log (don't forget to delete the old one) if the issue persists after remove optifine related things

I did everything what you written and updated minecolonies to newest alpha but same results. So the new debug -->
https://gist.github.com/perecnicek/717a092f62c699608bcbe1214a5731e4

**Comment by Nightenom** [comment]
That's the crash, definitely not our fault
```
[04Aug2020 20:44:04.329] [Server console handler/ERROR] [net.minecraft.server.dedicated.DedicatedServer/]: Caught previously unhandled exception :
java.io.IOError: java.io.IOException: Error executing 'stty -a': stty: 'standard input': Input/output error
	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:54) ~[jline-3.12.1.jar:?]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:650) ~[jline-3.12.1.jar:?]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418) ~[jline-3.12.1.jar:?]
	at net.minecraftforge.server.console.TerminalHandler.handleCommands(TerminalHandler.java:61) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:100) ~[?:?]
Caused by: java.io.IOException: Error executing 'stty -a': stty: 'standard input': Input/output error
	at org.jline.utils.ExecHelper.exec(ExecHelper.java:42) ~[jline-3.12.1.jar:?]
	at org.jline.terminal.impl.ExecPty.doGetConfig(ExecPty.java:175) ~[jline-3.12.1.jar:?]
	at org.jline.terminal.impl.ExecPty.getAttr(ExecPty.java:87) ~[jline-3.12.1.jar:?]
	at org.jline.terminal.impl.ExecPty.doSetAttr(ExecPty.java:93) ~[jline-3.12.1.jar:?]
	at org.jline.terminal.impl.AbstractPty.setAttr(AbstractPty.java:29) ~[jline-3.12.1.jar:?]
	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:52) ~[jline-3.12.1.jar:?]
	... 4 more
[04Aug2020 20:44:04.338] [SIGCONT handler/INFO] [STDERR/]: [java.lang.Thread:dispatchUncaughtException:1956]: java.io.IOError: java.io.IOException: Error executing 'stty -a': stty: 'standard input': Input/output error
[04Aug2020 20:44:04.338] [SIGCONT handler/INFO] [STDERR/]: [java.lang.Thread:dispatchUncaughtException:1956]: 	at org.jline.terminal.impl.AbstractPosixTerminal.getAttributes(AbstractPosixTerminal.java:46)
[04Aug2020 20:44:04.338] [SIGCONT handler/INFO] [STDERR/]: [java.lang.Thread:dispatchUncaughtException:1956]: 	at org.jline.terminal.impl.AbstractTerminal.enterRawMode(AbstractTerminal.java:117)
[04Aug2020 20:44:04.338] [SIGCONT handler/INFO] [STDERR/]: [java.lang.Thread:dispatchUncaughtException:1956]: 	at org.jline.reader.impl.LineReaderImpl.handleSignal(LineReaderImpl.java:1043)
[04Aug2020 20:44:04.338] [SIGCONT handler/INFO] [STDERR/]: [java.lang.Thread:dispatchUncaughtException:1956]: 	at org.jline.terminal.impl.AbstractTerminal.raise(AbstractTerminal.java:81)
[04Aug2020 20:44:04.339] [SIGCONT handler/INFO] [STDERR/]: [java.lang.Thread:dispatchUncaughtException:1956]: 	at org.jline.terminal.impl.PosixSysTerminal.lambda$handle$1(PosixSysTerminal.java:65)
[04Aug2020 20:44:04.339] [SIGCONT handler/INFO] [STDERR/]: [java.lang.Thread:dispatchUncaughtException:1956]: 	at org.jline.utils.Signals.lambda$register$1(Signals.java:52)
[04Aug2020 20:44:04.339] [SIGCONT handler/INFO] [STDERR/]: [java.lang.Thread:dispatchUncaughtException:1956]: 	at com.sun.proxy.$Proxy23.handle(Unknown Source)
[04Aug2020 20:44:04.339] [SIGCONT handler/INFO] [STDERR/]: [java.lang.Thread:dispatchUncaughtException:1956]: 	at sun.misc.Signal$1.run(Signal.java:212)
[04Aug2020 20:44:04.339] [SIGCONT handler/INFO] [STDERR/]: [java.lang.Thread:dispatchUncaughtException:1956]: 	at java.lang.Thread.run(Thread.java:745)
[04Aug2020 20:44:04.339] [SIGCONT handler/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.io.IOException: Error executing 'stty -a': stty: 'standard input': Input/output error
[04Aug2020 20:44:04.339] [SIGCONT handler/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.jline.utils.ExecHelper.exec(ExecHelper.java:42)
[04Aug2020 20:44:04.339] [SIGCONT handler/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.jline.terminal.impl.ExecPty.doGetConfig(ExecPty.java:175)
[04Aug2020 20:44:04.339] [SIGCONT handler/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.jline.terminal.impl.ExecPty.getAttr(ExecPty.java:87)
[04Aug2020 20:44:04.339] [SIGCONT handler/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.jline.terminal.impl.AbstractPosixTerminal.getAttributes(AbstractPosixTerminal.java:44)
[04Aug2020 20:44:04.339] [SIGCONT handler/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 8 more
```
