### ISSUE TITLE
Crash when I put a personal schematic on my world.

### ISSUE THREAD

**Issue by 77Florian99** [ldtteam/Structurize#224]
Minecraft: 1.6.3
structurize: structurize-0.13.92-ALPHA-universal
Minecolonies: minecolonies-0.13.348-BETA-universal

Hello, when I put a custom schematic in my world, the game crashes directly.
I put my schematic file in the .minectaft/structurize/schematics location and I allowed players to put a custom schematic but the bug persists.

I have tested several other schematics but none of them work.
I also increased the ram allocated to minecraft to 8 GB but it still doesn't work. 

Here is my crashlog   

### Logs

https://gist.github.com/77Florian99/e7b2f34b22142c160020cb79247f3e4d

`---- Minecraft Crash Report ----
// There are four lights!

Time: 28/10/20 02:15
Description: mouseClicked event handler

java.lang.NullPointerException: mouseClicked event handler
	at com.minecolonies.coremod.client.gui.WindowMinecoloniesBuildTool.place(WindowMinecoloniesBuildTool.java:60) ~[?:0.13.348-BETA] {re:classloading}
	at com.ldtteam.structurize.client.gui.WindowBuildTool.confirmClicked(WindowBuildTool.java:1103) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.structurize.client.gui.WindowBuildTool$$Lambda$9073/715366504.run(Unknown Source) ~[?:?] {}
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.lambda$registerButton$0(AbstractWindowSkeleton.java:40) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton$$Lambda$9064/785522533.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:67) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.controls.Button.handleClick(Button.java:110) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.Pane.click(Pane.java:512) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$9111/637160577.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:351) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:304) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:166) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$9111/637160577.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:351) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:304) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:166) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.BOScreen.func_231044_a_(BOScreen.java:180) ~[?:0.13.92-ALPHA] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$5557/1969503994.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$5556/1750233521.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$4624/1734479232.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:384) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:973) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.25.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$467/1757032717.call(Unknown Source) [forge-1.16.3-34.1.25.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.minecolonies.coremod.client.gui.WindowMinecoloniesBuildTool.place(WindowMinecoloniesBuildTool.java:60) ~[?:0.13.348-BETA] {re:classloading}
	at com.ldtteam.structurize.client.gui.WindowBuildTool.confirmClicked(WindowBuildTool.java:1103) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.structurize.client.gui.WindowBuildTool$$Lambda$9073/715366504.run(Unknown Source) ~[?:?] {}
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.lambda$registerButton$0(AbstractWindowSkeleton.java:40) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton$$Lambda$9064/785522533.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:67) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.controls.Button.handleClick(Button.java:110) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.Pane.click(Pane.java:512) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$9111/637160577.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:351) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:304) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:166) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$9111/637160577.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:351) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:304) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:166) ~[?:0.13.92-ALPHA] {re:classloading}
	at com.ldtteam.blockout.BOScreen.func_231044_a_(BOScreen.java:180) ~[?:0.13.92-ALPHA] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$5557/1969503994.run(Unknown Source) ~[?:?] {}
-- Affected screen --
Details:
	Screen name: com.ldtteam.blockout.BOScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$5556/1750233521.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$4624/1734479232.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:mixin,re:classloading}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Trydeur'/131, l='ClientLevel', x=422.89, y=69.00, z=716.55]]
	Chunk stats: Client Chunk Cache: 1681, 1260
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,71,224), Chunk: (at 0,4,0 in 7,14; contains blocks 112,0,224 to 127,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1878420 game time, 2840337 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1974) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:600) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.25.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$467/1757032717.call(Unknown Source) [forge-1.16.3-34.1.25.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 895095416 bytes (853 MB) / 2091651072 bytes (1994 MB) up to 6429081600 bytes (6131 MB)
	CPUs: 8
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.25.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.25.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.25.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.25.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.16.3_HD_U_G4_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.25.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.25
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.25-client.jar Minecraft {minecraft@1.16.3 DONE}
		mcw-bridges-1.0.4-mc1.16.3.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		backpacked-1.5.2-1.16.3.jar Backpacked {backpacked@1.5.2 DONE}
		VanillaTweaks-1.16.3-1.5.33 (2).jar VanillaTweaks {vanillatweaks@1.16.3-1.5.33 DONE}
		DungeonCrawl-1.16.3-2.1.1.jar Dungeon Crawl {dungeoncrawl@2.1.1 DONE}
		AmbientSounds_v3.0.21_mc1.16.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		structurize-0.13.92-ALPHA-universal.jar Structurize {structurize@0.13.92-ALPHA DONE}
		worldedit-forge-mc1.16.3-7.2.0-rc2-dist.jar WorldEdit {worldedit@7.2.0-rc2+a615e01 DONE}
		BiomesOPlenty-1.16.3-12.0.0.409-universal.jar Biomes O' Plenty {biomesoplenty@1.16.3-12.0.0.409 DONE}
		minecolonies-0.13.348-BETA-universal.jar Minecolonies {minecolonies@0.13.348-BETA DONE}
		simpleplanes-1.16.3-3.1.0.0.jar Simple Planes {simpleplanes@1.16.3-3.1.0.0 DONE}
		SimpleCoreLib-1.16.3-2.0.1.2.jar SimpleCoreLib {simplecorelib@1.16.3-2.0.1.2 DONE}
		jei-1.16.3-7.6.0.49.jar Just Enough Items {jei@7.5.0.43 DONE}
		forge-1.16.3-34.1.25-universal.jar Forge {forge@34.1.25 DONE}
		AppleSkin-mc1.16.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		FastLeafDecay-v25.jar FastLeafDecay {fastleafdecay@v25 DONE}
		SimpleOres2-1.16.3-2.3.1.0.jar Simple Ores {simpleores@1.16.3-2.3.1.0 DONE}
		healingcf_1.16.3-3.1.jar Healing Campfire {healingcf@3.1 DONE}
		collective-1.16.3-1.53.jar Collective {collective@1.53 DONE}
		betterweather-1.0.3.jar Better Weather {betterweather@1.0.1 DONE}
		dungeons_gear-1.16.2+1.16.3-2.0.0.jar Dungeons Gear {dungeons_gear@2.0.0 DONE}
		corpse-1.16.3-1.0.6.jar Corpse {corpse@1.16.3-1.0.6 DONE}
	Crash Report UUID: 988879c3-00e9-410d-a421-19edd764645b
	Launched Version: 1.16.3-forge-34.1.25
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.86, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources
	Current Language: Français (France)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	OptiFine Version: OptiFine_1.16.3_HD_U_G4_pre2
	OptiFine Build: 20201007-190609
	Render Distance Chunks: 18
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.2.01pre1.zip
	OpenGlVersion: 4.6.0 NVIDIA 430.86
	OpenGlRenderer: GeForce GTX 1070 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8`

**Comment by Raycoms** [comment]
Does the custom schematic render on your side?

**Comment by Raycoms** [comment]
Can we have the latest log previous to the crash?

**Comment by 77Florian99** [comment]
The schematic does not appear and the preview of the structurize build tool does not work.
here is the lastest log 
https://gist.github.com/77Florian99/8036f9f03e432c868eb8e676fa3b38bc

Thank you in any case for your prompt response!

**Comment by Raycoms** [comment]
yeah, if the schematic doesn't appear and you click place it will crash yes.

**Comment by 77Florian99** [comment]
I also tried to use the name of a native schematic of the mod minecolonies to replace its model and its crash still as much.
and you have why it doesn't appear in the preview?

**Comment by ravenbuilder934** [comment]
Does this still happen on the latest versions?
