### ISSUE TITLE
java.lang.RuntimeException: Missing some newest data versions. Please update com/ldtteam/structures/blueprints/v1/DataVersion

### ISSUE THREAD

**Issue by Hellfire1317** [ldtteam/Structurize#287]
Hello Everyone,

Me and my friend wanted to add MineColony to our 1.16.5 Server (1.16.4 and 1.16.5 should be compatible as stated by Mojang)

Now it crashes during initialisation. I tried multiple Release, Beta aswell as Alpha files. None did work.

Full error log down below:
```
-- Head --
Thread: Render thread
Stacktrace:
	at com.ldtteam.structurize.Structurize.<init>(Structurize.java:47) ~[structurize:0.13.100-RELEASE] {re:classloading}
-- MOD structurize --
Details:
	Mod File: structurize-0.13.100-RELEASE-universal.jar
	Failure message: Structurize (structurize) has failed to load correctly
		java.lang.RuntimeException: Missing some newest data versions. Please update com/ldtteam/structures/blueprints/v1/DataVersion
	Mod Version: 0.13.100-RELEASE
	Mod Issue URL: https://github.com/ldtteam/Structurize/issues/new
	Exception message: java.lang.RuntimeException: Missing some newest data versions. Please update com/ldtteam/structures/blueprints/v1/DataVersion
Stacktrace:
	at com.ldtteam.structurize.Structurize.<init>(Structurize.java:47) ~[structurize:0.13.100-RELEASE] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?] {re:classloading,re:classloading}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?] {}
	at java.lang.Class.newInstance(Class.java:584) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.0] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.8.0-7642-generic
	Java Version: 11.0.9.1, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 665309640 bytes (634 MB) / 1577058304 bytes (1504 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.14.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.14.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.0.14.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.14.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.14.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.14
	FML Language Providers: 
		javafml@36.0
		minecraft@1
	Mod List: 
		forge-1.16.5-36.0.14-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|NOSIGNATURE
		elevatorid-1.16.5-1.7.12.jar                      |Elevator Mod                  |elevatorid                    |1.16.5-1.7.12       |CREATE_REG|NOSIGNATURE
		structurize-0.13.100-RELEASE-universal.jar        |Structurize                   |structurize                   |0.13.100-RELEASE    |ERROR     |NOSIGNATURE
		Bookshelf-1.16.5-10.0.1.jar                       |Bookshelf                     |bookshelf                     |10.0.1              |CREATE_REG|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		EnchantmentDescriptions-1.16.5-7.0.2.jar          |EnchantmentDescriptions       |enchdesc                      |7.0.2               |CREATE_REG|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		ImmersiveEngineering-1.16.5-4.2.1-131.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-4.2.1-131    |CREATE_REG|44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		minecolonies-0.13.480-BETA-universal.jar          |Minecolonies                  |minecolonies                  |0.13.480-BETA       |CREATE_REG|NOSIGNATURE
		jei-1.16.4-7.6.1.70.jar                           |Just Enough Items             |jei                           |7.6.1.70            |CREATE_REG|NOSIGNATURE
		forge-1.16.5-36.0.14-universal.jar                |Forge                         |forge                         |36.0.14             |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Aquaculture-1.16.4-2.1.12.jar                     |Aquaculture 2                 |aquaculture                   |1.16.4-2.1.12       |CREATE_REG|NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v1a          |CREATE_REG|5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		Chisels-and-Bits-Mod-1.16.5.jar                   |Chisels & bits                |chiselsandbits                |NONE                |CREATE_REG|NOSIGNATURE
		Waystones_1.16.3-7.3.1.jar                        |Waystones                     |waystones                     |7.3.1               |CREATE_REG|NOSIGNATURE
		appliedenergistics2-8.2.0.jar                     |Applied Energistics 2         |appliedenergistics2           |8.2.0               |CREATE_REG|95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		NaturesCompass-1.16.5-1.8.6.jar                   |Nature's Compass              |naturescompass                |1.16.5-1.8.6        |CREATE_REG|NOSIGNATURE
	Crash Report UUID: 9916a7d0-8a21-4ede-82e8-5591f6ffc74e
	OptiFine Version: OptiFine_1.16.5_HD_U_G6
	OptiFine Build: 20210117-013236
	Render Distance Chunks: 24
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Chocapic13_V9_Ultra.zip
	OpenGlVersion: 4.6 (Compatibility Profile) Mesa 20.3.2
	OpenGlRenderer: Radeon RX Vega (VEGA10, DRM 3.38.0, 5.8.0-7642-generic, LLVM 11.0.0)
	OpenGlVendor: AMD 
	CpuCount: 16
```

**Comment by Nightenom** [comment]
Download latest alpha <https://www.curseforge.com/minecraft/mc-mods/structurize/files/all> for your version
