### ISSUE TITLE
Chunk issue, empty/not accessible around Walls - fancy barbican when leaving chunkloaded area

### ISSUE THREAD

**Issue by ederlezi29** [ldtteam/Structurize#345]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: structurize-0.13.163-ALPHA-universal.jar
- MineColonies Version (if related bug):
- Related Mods and their Versions:

## Expected behavior
Every chunks in game are supposed to be displayed

## Actual behavior
Some chunks are disappearing, leaving empty world when you are leaving the area. It is always around the Walls fancy Barbican.

## Steps to reproduce the issue

1. Leave a chunk loaded area or log off. 
2. Come back or log back in.
3.

### Logs

- latest.log: https://gist.github.com/ederlezi29/dc95c16b6dce0cdf89b965f2d4022d68
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ederlezi29** [comment]
Here is the issue:

[10Apr2021 10:14:31.918] [Server thread/ERROR] [net.minecraft.world.chunk.Chunk/]: A TileEntity type com.ldtteam.structurize.tileentities.TileEntityMultiBlock has thrown an exception trying to write state. It will not persist, Report this to the mod author
java.lang.RuntimeException: class com.ldtteam.structurize.tileentities.TileEntityMultiBlock is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.func_189516_d(TileEntity.java:64) ~[?:?]
	at net.minecraft.tileentity.TileEntity.func_189515_b(TileEntity.java:58) ~[?:?]
	at com.ldtteam.structurize.tileentities.TileEntityMultiBlock.func_189515_b(TileEntityMultiBlock.java:365) ~[structurize:0.13.163-ALPHA]
	at net.minecraft.world.chunk.Chunk.func_223134_j(Chunk.java:427) ~[?:?]
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222645_a(ChunkSerializer.java:287) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219229_a(ChunkManager.java:682) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_282]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_282]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_282]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_282]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_282]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_282]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_282]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_282]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_282]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_282]
	at net.minecraft.world.server.ChunkManager.func_219177_a(ChunkManager.java:337) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217210_a(ServerChunkProvider.java:307) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:698) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:531) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:567) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:514) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:678) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

**Comment by Raycoms** [comment]
Fixed in next structurize version
