### ISSUE TITLE
Structurize failing to load properly

### ISSUE THREAD

**Issue by Haelis** [ldtteam/Structurize#369]
### Prerequisites 

- [ x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- Structurize Version:

## Problem description

Structurize is saying that I don't have the newest update to use/run, yet I have doubled and tripled checked that it is completely up to date and it continues to fail loading correctly.
Bug report below.

[Structurize Bug Reort.txt](https://github.com/ldtteam/Structurize/files/6410257/Structurize.Bug.Reort.txt)

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 5/1/21 3:22 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$6312/1529070070.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:418) [?:?] {re:classloading,xf:FakeOptiFine:default,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$6087/1076847093.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:FakeOptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:classloading,pl:accesstransformer:B,xf:FakeOptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.4.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$500/1790598448.call(Unknown Source) [forge-1.16.5-36.1.4.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.ldtteam.structurize.Structurize.<init>(Structurize.java:47) ~[?:0.13.100-RELEASE] {re:classloading}
-- MOD structurize --
Details:
	Mod File: structurize-0.13.100-RELEASE-universal.jar
	Failure message: Structurize (structurize) has failed to load correctly
		java.lang.RuntimeException: Missing some newest data versions. Please update com/ldtteam/structures/blueprints/v1/DataVersion
	Mod Version: 0.13.100-RELEASE
	Mod Issue URL: https://github.com/ldtteam/Structurize/issues/new
	Exception message: java.lang.RuntimeException: Missing some newest data versions. Please update com/ldtteam/structures/blueprints/v1/DataVersion
Stacktrace:
	at com.ldtteam.structurize.Structurize.<init>(Structurize.java:47) ~[?:0.13.100-RELEASE] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.1] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3093/1075708596.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3183/885876140.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3284140592 bytes (3132 MB) / 4719640576 bytes (4501 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.16.4_HD_U_G6_pre12.jar OptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.5-0.5.5.jar optiforge TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.4.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.5-0.5.5.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.5-0.5.5.jar optiforgewrapper TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.4
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		Tabula-1.16.5-10.2.0.jar                          |Tabula                        |tabula                        |10.2.0              |CREATE_REG|NOSIGNATURE
		Wyrmroost-1.16.3-1.2.11.jar                       |Wyrmroost                     |wyrmroost                     |1.16.3-1.2.11       |CREATE_REG|NOSIGNATURE
		spiders-2.0-1.16.4-1.0.4.jar                      |Spiders 2.0                   |spiderstpo                    |1.0.4               |CREATE_REG|NOSIGNATURE
		treeharvester_1.16.5-2.4.jar                      |Tree Harvester                |treeharvester                 |2.4                 |CREATE_REG|NOSIGNATURE
		Uppers-0.3.2.jar                                  |Uppers                        |uppers                        |0.3.2               |CREATE_REG|NOSIGNATURE
		wonderful-enchantments-1.16.4-1.2.0.jar           |Wonderful Enchantments        |wonderful_enchantments        |1.2.0               |CREATE_REG|NOSIGNATURE
		reap-1.16.5-1.0.0.jar                             |Reap Mod                      |reap                          |1.16.5-1.0.0        |CREATE_REG|NOSIGNATURE
		pitg-1.16.3-1.4.2.jar                             |Pane In The Glass             |pitg                          |1.16.3-1.4.2        |CREATE_REG|NOSIGNATURE
		Neat 1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |CREATE_REG|NOSIGNATURE
		Waystones_1.16.5-7.4.0.jar                        |Waystones                     |waystones                     |7.4.0               |CREATE_REG|NOSIGNATURE
		tumbleweed-1.16-0.4.9.jar                         |Tumbleweed                    |tumbleweed                    |1.16-0.4.9          |CREATE_REG|NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |CREATE_REG|NOSIGNATURE
		YungsApi-1.16.4-Forge-6.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |CREATE_REG|NOSIGNATURE
		VanillaTweaks-1.16.4-1.5.39.jar                   |VanillaTweaks                 |vanillatweaks                 |1.16.4-1.5.39       |CREATE_REG|NOSIGNATURE
		upstream-1.0.jar                                  |Upstream                      |upstream                      |1.0                 |CREATE_REG|NOSIGNATURE
		sophisticatedbackpacks-1.16.4-2.4.0.259.jar       |Sophisticated Backpacks       |sophisticatedbackpacks        |property(class java.|CREATE_REG|NOSIGNATURE
		Omni-1.16.4-1.2.1.jar                             |Omni                          |omni                          |version             |CREATE_REG|NOSIGNATURE
		WaterStrainer-1.16.3-10.0.0.jar                   |Water Strainer                |waterstrainer                 |1.16.3-10.0.0       |CREATE_REG|NOSIGNATURE
		iChunUtil-1.16.5-10.2.0.jar                       |iChunUtil                     |ichunutil                     |10.2.0              |CREATE_REG|NOSIGNATURE
		traverse-1.16.4-0.4.3.8.jar                       |Traverse: Reforged            |traverse                      |1.16.4-0.4.3.8      |CREATE_REG|NOSIGNATURE
		Paraglider-1.16.2-1.3.1.0.jar                     |Paraglider                    |paraglider                    |1.3.1.0             |CREATE_REG|NOSIGNATURE
		forge-1.16.5-36.1.4-universal.jar                 |Forge                         |forge                         |36.1.4              |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		PassthroughSigns-1.16.4-2.3.7.jar                 |Passthrough Signs             |passthroughsigns              |1.16.4-2.3.7        |CREATE_REG|NOSIGNATURE
		stackrefill_1.16.5-1.7.jar                        |Stack Refill                  |stackrefill                   |1.7                 |CREATE_REG|NOSIGNATURE
		TridentReturn-1.16.4-0.1.jar                      |TridentReturn                 |tridentreturn                 |1.16.4-0.1          |CREATE_REG|NOSIGNATURE
		scuba-gear-1.16.5-1.0.3.jar                       |Scuba Gear                    |scuba_gear                    |1.0.3               |CREATE_REG|NOSIGNATURE
		RevampedWolf-1.16.4-0.7.1.jar                     |RevampedWolf                  |revampedwolf                  |1.16.4-0.7.1        |CREATE_REG|NOSIGNATURE
		OffHandCombat-1.16.3-3.2.0.3.jar                  |Off Hand Combat               |offhandcombat                 |1.16.3-3.2.0.3      |CREATE_REG|c9:84:cd:eb:27:ac:0d:ad:8c:55:6f:d6:5f:19:f2:c8:63:2a:b0:bd:3b:d0:b6:df:fd:9f:de:9f:9d:e8:7c:68
		supplementaries-1.16.5-0.12.1.jar                 |Supplementaries               |supplementaries               |1.16.5-0.12.1       |CREATE_REG|NOSIGNATURE
		structure_gel-1.16.5-1.7.7.jar                    |Structure Gel API             |structure_gel                 |1.7.7               |CREATE_REG|NOSIGNATURE
		forge-1.16.5-36.1.4-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|NOSIGNATURE
		cofh_core-1.16.4-1.2.1.jar                        |CoFH Core                     |cofh_core                     |1.2.1               |CREATE_REG|NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |CREATE_REG|NOSIGNATURE
		roughtweaks-1.16.5-2.2.4.jar                      |Rough Tweaks                  |roughtweaks                   |2.2.4               |CREATE_REG|NOSIGNATURE
		ToolBelt-1.16.5-1.16.0.jar                        |Tool Belt                     |toolbelt                      |1.16.0              |CREATE_REG|NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |CREATE_REG|NOSIGNATURE
		skinned_lanterns-1.16.5-1.3.1.jar                 |Skinned Lanterns              |skinnedlanterns               |1.16.5-1.3.1        |CREATE_REG|NOSIGNATURE
		omgourd-1.16.4-1.2.0.jar                          |Oh My Gourd                   |omgourd                       |1.2.0               |CREATE_REG|NOSIGNATURE
		majrusz-library-1.16.4-1.5.0.jar                  |Majrusz Library               |majrusz_library               |1.5.0               |CREATE_REG|NOSIGNATURE
		playerex-1.1.7.5-1.16.4.jar                       |Player Ex                     |playerex                      |1.1.7.5             |CREATE_REG|NOSIGNATURE
		SpartanShields-1.16.5-2.1.2.jar                   |Spartan Shields               |spartanshields                |2.1.2               |CREATE_REG|NOSIGNATURE
		Patchouli-1.16.4-50.jar                           |Patchouli                     |patchouli                     |1.16.4-50           |CREATE_REG|NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |CREATE_REG|NOSIGNATURE
		collective-1.16.5-2.26.jar                        |Collective                    |collective                    |2.26                |CREATE_REG|NOSIGNATURE
		StorageDrawers-1.16.3-8.2.2.jar                   |Storage Drawers               |storagedrawers                |8.2.2               |CREATE_REG|NOSIGNATURE
		sit-1.16.5-v1.3.1.jar                             |Sit                           |sit                           |v1.3.1              |CREATE_REG|NOSIGNATURE
		Regrowth-1.16.4-1.16.4-1.35.0.18.jar              |Regrowth Mod                  |regrowth                      |1.16.4-1.35.0.18    |CREATE_REG|NOSIGNATURE
		structurize-0.13.100-RELEASE-universal.jar        |Structurize                   |structurize                   |0.13.100-RELEASE    |ERROR     |NOSIGNATURE
		TheAbyss2+1.9.7+1.16.5.jar                        |TheAbyss                      |theabyss                      |1.9.7               |CREATE_REG|NOSIGNATURE
		SpartanWeaponry-1.16.4-2.1.0-beta-4.jar           |Spartan Weaponry              |spartanweaponry               |2.1.0 beta 4        |CREATE_REG|NOSIGNATURE
		wandering_trapper-1.16.2-0.1.1.jar                |Wandering Trapper             |wandering_trapper             |1.16.2-0.1.0        |CREATE_REG|NOSIGNATURE
		sapience-1.16.4-1.1.1.jar                         |Sapience                      |sapience                      |1.1.1               |CREATE_REG|NOSIGNATURE
		SoundFilters-0.14_for_1.16.2.jar                  |Sound Filters                 |soundfilters                  |0.14_for_1.16.2     |CREATE_REG|NOSIGNATURE
		xptome-1.16.5-v2.1.jar                            |XP Tome                       |xpbook                        |v2.1                |CREATE_REG|NOSIGNATURE
	Crash Report UUID: d0ec0c91-fe94-4770-b3e2-992eb52a8c4a
	OptiFine Version: OptiFine_1.16.4_HD_U_G6_pre12
	OptiFine Build: 20210110-191159
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 461.72
	OpenGlRenderer: GeForce RTX 2070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by someaddons** [comment]
The error literally already tells you to update, update!

**Comment by Haelis** [comment]
except, I did, and it literally, did >nothing< except for telling me to update to something that isn't possible to update!

**Comment by Haelis** [comment]
>>>Structurize is saying that I don't have the newest update to use/run, yet I have doubled and tripled checked that it is completely up to date and it continues to fail loading correctly. <<<< I mentioned it, in the description. I've checked over and over to update it, it doesn't do it correctly. Ergo, it fails.

**Comment by Haelis** [comment]
Either way, both mods need serious updating/fixing for bugs!

**Comment by ravenbuilder934** [comment]
No, they don't. Use the **latest alpha** of both mods.
