### ISSUE TITLE
log spam when using build tool

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/Structurize#653]
ouf-of-jar should not be used if path is from jar, or the namespace must match modid if path given to ouf-of-jar is from jar
![image](https://github.com/ldtteam/Structurize/assets/17338378/55fb58af-1777-440b-ad5e-df6e5bb7d58a)
```
[14:25:39] [Render thread/WARN] [minecraft/TextureManager]: Failed to load texture: structurize:blueprints/minecolonies/fortress/fortress.png
java.io.FileNotFoundException: structurize:blueprints/minecolonies/fortress/fortress.png
        at net.minecraft.server.packs.resources.ResourceProvider.lambda$getResourceOrThrow$0(ResourceProvider.java:16) ~[neoforge-20.4.159-beta.jar:?] {re:classloading}
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {}
        at net.minecraft.server.packs.resources.ResourceProvider.getResourceOrThrow(ResourceProvider.java:16) ~[neoforge-20.4.159-beta.jar:?] {re:classloading}
        at net.minecraft.client.renderer.texture.SimpleTexture$TextureImage.load(SimpleTexture.java:83) ~[neoforge-20.4.159-beta.jar:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.client.renderer.texture.SimpleTexture.getTextureImage(SimpleTexture.java:57) ~[neoforge-20.4.159-beta.jar:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.client.renderer.texture.SimpleTexture.load(SimpleTexture.java:30) ~[neoforge-20.4.159-beta.jar:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.client.renderer.texture.TextureManager.loadTexture(TextureManager.java:92) ~[neoforge-20.4.159-beta.jar:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.client.renderer.texture.TextureManager.register(TextureManager.java:63) ~[neoforge-20.4.159-beta.jar:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.client.renderer.texture.TextureManager.getTexture(TextureManager.java:113) ~[neoforge-20.4.159-beta.jar:?] {re:classloading,pl:runtimedistcleaner:A}
```

**Comment by Nightenom** [comment]
Was already fixed somewhen
