### ISSUE TITLE
[0.10.247] Malformed Json Exception

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/Structurize#95]
Just updated my server for Foreshadowing to build 247 and got malformed json exception

```
[16:16:30] [Server thread/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 2 errors found
[16:16:30] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Structurize (structurize) has failed to load correctly
§7com.google.gson.stream.MalformedJsonException: Unterminated object at line 1114 column 4 path $.,
        Minecolonies (minecolonies) has failed to load correctly
§7com.google.gson.stream.MalformedJsonException: Unterminated object at line 1114 column 4 path $.
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:611) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222] {}
```

Issue:  0.10.247-alpha crashes dedicated server Forge 1.15.2 build 31.1.1

Notes:
     malformed json exception

crash report:
http://paste.ubuntu.com/p/9Jvx937HTb/

fml server latest:
http://paste.ubuntu.com/p/tFHVG47ddh/

**Comment by kreezxil** [comment]
Deleting the existing structurize config files do not help at all.

Could it be that 1.15.2 uses TOML files and someone fubarred and made this version start reading and expecting json again?

**Comment by kreezxil** [comment]
I was able to get past this by rolling down to build 246

**Comment by Nightenom** [comment]
~Not a structurize error, if you read carefully it's minecolonies, which version you have?~

**Comment by Nightenom** [comment]
And it's json exception, so toml can't be involved
